Fix Broken Logic for Empty Regions
aukaost/SublimePrettyYAML pull request #2
Opened 2020-04-23 13:54 UTC by TheSecEng

Currently, if you have multiple regions selected, and one of them is empty, we try to format the entire document, which is clearly wrong. This fixes it by check if the region is empty and if there is only one region.

2020-04-28 09:52 UTC, aukaost commented
Thanks for this PR! I've not pushed a release in a very long time, let me find out how one does this again and then I'll test, merge and release it 😃 .

2020-04-28 15:11 UTC, TheSecEng commented
@aukaost likely more PR's to come, potentially aligning with changes made recently in Pretty JSON

2020-05-03 22:12 UTC, aukaost requested changes

2020-05-03 22:12 UTC, aukaost commented on PrettyYaml.py
> +                selection = sublime.Region(0, view.size())
`view` is now undefined.
https://github.com/dzhibas/SublimePrettyJson/blob/4c66146fc967be2b848fa003b4cd55d18c39c3b4/PrettyJson.py#L101
This function takes in `view` as an argument, leaving it as `self.view` here is fine.

2020-05-04 13:13 UTC, TheSecEng commented on PrettyYaml.py
> +                selection = sublime.Region(0, view.size())
Good catch.

2020-05-04 13:52 UTC, aukaost approved these changes

2020-05-04 13:53 UTC, merged